// KQL script
// Use management commands in this script to configure your database items, such as tables, functions, materialized views, and more.


.create-merge table flights_raw (FlightDate:datetime, Status:string, DepartureIATA:string, DepartureDelay:string, DepartureSched:datetime, ArrivalIATA:string, ArriivalSched:datetime, ArrivalDelay:string, Airline:string, FlightNumber:string, IngestedAt:datetime) 
